configuration: Release
image: Visual Studio 2017
platform: x64

cache: c:\tools\vcpkg\installed\

install:
    - cd C:\projects\libswf && git submodule update --init --recursive
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - cd C:\Tools\vcpkg && git pull && .\bootstrap-vcpkg.bat && cd %APPVEYOR_BUILD_FOLDER%
    - vcpkg install zlib:x64-windows zlib:x64-windows-static
    - vcpkg integrate install

before_build:
    - mkdir build && cd build
    - cmake ..
       -DCMAKE_BUILD_TYPE:STRING=Release
       -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
       -G "Visual Studio 15 2017 Win64"

build:
    project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln